require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - bin/rake
    - bin/rspec
    - bin/rubocop
    - "tmp/**/*"
    - "vendor/**/*"

Metrics/BlockLength:
  Exclude:
    - dualcone.gemspec
    - "spec/**/*"

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - "ext/**/*"
