AllCops:
  Exclude:
    - bin/rake
    - bin/rspec
    - bin/rubocop
    - "vendor/**/*"

Metrics/BlockLength:
  Exclude:
    - dualcone.gemspec
    - "spec/**/*"

Style/GlobalVars:
  Exclude:
    - "ext/**/*"
